[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
etcetera = "0.10.0"
once_cell = "1.21.3"
serde_json = "1.0"
tempfile = "3.0"
log = "0.4"
env_logger = "0.11"
fs2 = "0.4.3"

[[bin]]
name = "c"
path = "src/main.rs"

